server:
  port: 8081

spring:
  application:
    name: iap-ios-service

# Apple App Store Configuration (for development/testing)
apple:
  app-store:
    key-id: "MOCK_KEY_ID"
    issuer-id: "mock-issuer-id-12345678-1234-1234-1234-123456789012"
    bundle-id: "com.example.mock.app"
    private-key: |
      -----BEGIN PRIVATE KEY-----
      MOCK_PRIVATE_KEY_CONTENT_FOR_DEVELOPMENT_TESTING_ONLY
      -----END PRIVATE KEY-----

logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG