package com.example.integration.domain

enum class WebhookNotificationType {
    // Google Play Notifications
    SUBSCRIPTION_RECOVERED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_CANCELED,
    SUBSCRIPTION_PURCHASED,
    SUBSCRIPTION_ON_HOLD,
    SUBSCRIPTION_IN_GRACE_PERIOD,
    SUBSCRIPTION_RESTARTED,
    SUBSCRIPTION_PRICE_CHANGE_CONFIRMED,
    SUBSCRIPTION_DEFERRED,
    SUBSCRIPTION_PAUSED,
    SUBSCRIPTION_PAUSE_SCHEDULE_CHANGED,
    SUBSCRIPTION_REVOKED,
    SUBSCRIPTION_EXPIRED,
    
    // App Store Notifications
    INITIAL_BUY,
    CANCEL,
    RENEWAL,
    INTERACTIVE_RENEWAL,
    DID_CHANGE_RENEWAL_PREF,
    DID_CHANGE_RENEWAL_STATUS,
    DID_FAIL_TO_RENEW,
    DID_RECOVER,
    PRICE_INCREASE_CONSENT,
    REFUND,
    REVOKE,
    
    // Common
    UNKNOWN
}